version: "3.8"
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
  sender:
    image: suraj362/sender:${build}
    container_name: sender
    ports:
      - "8082:8082"
    volumes:
      - ./sender:/app
    depends_on: 
      - rabbitmq
  receiver:
    image: suraj362/receiver:${build}
    container_name: receiver
    ports:
      - "8081:8081"
    volumes:
      - ./receiver:/app
    depends_on:
      - rabbitmq
      - sender
